language: ruby
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_dev.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_dev.gemfile

before_install:
  # https://docs.travis-ci.com/user/languages/ruby/#bundler
  - RUBY_VERSION=$(ruby -v | grep -o -E '[0-9]\.[0-9]' | tr -d '.')
  # Bundler for greater than Ruby 2.3 version
  - gem update --system
  - gem install bundler -v '>= 2'
